language: go

go:
  - 1.7
  - 1.8
  - 1.9

install:
  - go get github.com/relnod/calcgo
  - go get github.com/mattn/goveralls
  - go get -v github.com/golang/lint/golint
  - go get -t -v ./...

script:
  - diff <(gofmt -d .) <(echo -n)
  - go vet -x ./...
  - golint ./...
  - go test -v -race ./...
  - $GOPATH/bin/goveralls -service=travis-ci
